[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    Wifi
    WiFiManager
    PubSubClient
    NTPClient
    ADS1115_WE
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
